//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prototipo_1._3.BD.RRHH
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_empleado()
        {
            this.tbl_expediente = new HashSet<tbl_expediente>();
            this.tbl_registroIncapacidad = new HashSet<tbl_registroIncapacidad>();
            this.tbl_usuario = new HashSet<tbl_usuario>();
        }
    
        public int Id_empleado { get; set; }
        public string Nombre { get; set; }
        public string Primer_apellido { get; set; }
        public string Segundo_apellido { get; set; }
        public string Direccion { get; set; }
        public int Telefono { get; set; }
        public string Correo { get; set; }
        public string Estado_civil { get; set; }
        public System.DateTime Fecha_naci { get; set; }
        public int Id_departamento { get; set; }
        public int Id_rol { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual tbl_departamento tbl_departamento { get; set; }
        public virtual tbl_roles tbl_roles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_expediente> tbl_expediente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_registroIncapacidad> tbl_registroIncapacidad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_usuario> tbl_usuario { get; set; }
    }
}
